//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ReciveDates = new HashSet<ReciveDate>();
            this.Car_properties = new HashSet<Car_properties>();
        }
    
        public int Car_Id { get; set; }
        public string Type_Of_Car { get; set; }
        public string Car_Brand { get; set; }
        public string Car_Model { get; set; }
        public string Chassis_No { get; set; }
        public double price_in_day { get; set; }
        public string photo_Car { get; set; }
        public string Agince_ID { get; set; }
    
        public virtual Agince Agince { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciveDate> ReciveDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car_properties> Car_properties { get; set; }
    }
}
